### PR TITLE
"for of" loop is not supported by legacy browsers.

### PR DESCRIPTION
**Pull request by rcastera**
-Adding babel-polyfill for supporting older browsers
-Resolves #247 
-Resolves error `ReferenceError: Can't find variable: Symbol in bower_components/twitter-text/js/pkg/twitter-text-2.0.2.js (line 854)`

### CODE REVIEW

**Comment by kaushlakers** [comment]
I don't think we need to whole polyfill package for just startsWIth. I've substituted it with substring in this patch. 

https://github.com/twitter/twitter-text/pull/244

**Comment by rcastera** [comment]
This isn't just for `startsWith`. I still have an issue with twitter-text running in Phantomjs failing with this error `TypeError: undefined is not a function (evaluating 'labels[Symbol.iterator]()')`.

We have many tests that are failing when upgrading to the newer version of twitter-text due to lack of support. One of your dependencies bundled in the library has the same issue: `punycode`

This error exists in the travis builds as well: https://travis-ci.org/twitter/twitter-text/jobs/333552627

**Comment by rcastera** [comment]
See this for an explanation: https://github.com/babel/babel-loader/issues/84

**Comment by kaushlakers** [comment]
@rcastera good point. I don't think it's twitter-text's responsibility as a text parsing library to polyfill browser features for legacy browsers. We use [this polyfill](https://github.com/medikoo/es6-symbol) internally.

As a follow up, I can try to raise a PR to the [punycode.js](https://github.com/bestiejs/punycode.js/blob/master/punycode.js#L302) lib to replace the "for of" loops. From what I can see, we can safely change it to use a for loop since it is always an array.

**Comment by hansott** [comment]
You can apply these patches:
https://github.com/engagor/twitter-text/commit/176e1641ca38251d879c36ed56c3f5a2bfc25d86
https://github.com/engagor/punycode.js/commit/467e825a9a54a8a62c58dd591d6e410607089159

**Comment by kaushlakers** [comment]
@hansott are you planning to raise a PR to punycode or shall I go ahead? :)

**Comment by hansott** [comment]
@kaushlakers Feel free to do so 😉

**Comment by rcastera** [comment]
Thanks @kaushlakers @hansott 

@kaushlakers will you create a PR to apply [this patch](https://github.com/engagor/twitter-text/commit/176e1641ca38251d879c36ed56c3f5a2bfc25d86) as well?

**Comment by kaushlakers** [comment]
Created this. Hoping we can get this merged and published. We can apply @hansott's patch to twitter-text as well

https://github.com/bestiejs/punycode.js/pull/74

**Comment by rcastera** [comment]
@kaushlakers I'll update this PR with the patch. Thanks!

**Comment by rcastera** [comment]
@kaushlakers updated the PR. I also removed this [unused variable](https://github.com/twitter/twitter-text/pull/248/files#diff-caf1de29ac56240c931474c27fbfbfbcL17)

**Pull request merged**
