### PR TITLE
Extract IP and Email addresses.

### PR DESCRIPTION
**Pull request by Azdy-dev**
In order to extract IP and email  address from text, i added email and IP extractors.
thanks.

### CODE REVIEW

**Comment by Azdy-dev** [comment]
I don't know why it fails.

**Comment by andypiper** [comment]
Inclined to agree with @leeaustinadams here, these are not entities that we document in the API, so I'd advocate for not added to twitter-text as a tokenizer.

**Comment by Azdy-dev** [comment]
> Inclined to agree with @leeaustinadams here, these are not entities that we document in the API, so I'd advocate for not adding to twitter-text as a tokenizer.

Thanks, based on the library name as twitter-text , I agree with you. But, as entity-extractor, I prefer this commit. As a result, I think, it's better to consider the library name.

**Comment by kaushlakers** [comment]
Agree with both @andypiper and @leeaustinadams here. This change is beyond the scope of what this library should support given that these entities aren't supported in the Twitter product. 
@Azdy-dev Appreciate your PR that sparked this discussion 😃

**Pull request closed without merging**
